### ISSUE TITLE
Multiline Headers

### ISSUE THREAD

**Issue by stuntguy3000** [mkotb/ConfigAPI#8]
Is there a way to do Multiline headers?

Whilst `HeaderComments` allows a `String[]` to be passed, there is no way to actually create a String array for a class annotation.

**Attribute value must be constant.**

**Comment by mkotb** [comment]
It would look like the following:

```java
@HeaderComments({
   "This is a config file",
   "you can change fields",
   "yay"
})
public class MyConfig {
    // your fields and stuff
}
```

**Comment by stuntguy3000** [comment]
Cheers.
